name: Build QSV Encoder Image with Intel Cartwheel FFmpeg

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  ENCODER: qsv-cartwheel
  VERSION: 0.12.0-4

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./qsv/cartwheel
          push: true
          tags: |
            ghcr.io/ttys0/other-transcode:${{ env.ENCODER }}-latest
            ghcr.io/ttys0/other-transcode:${{ env.ENCODER }}-${{ env.VERSION}}
